application: lilydjwg # that's the *** part in ***.appspost.com.
version: test
runtime: python
api_version: 1

handlers:
- url: /_ah/xmpp/.*
  script: chatmain.py
- url: /_admin/user.*
  script: usermaintainer.py
  login: admin
- url: /_admin/stat
  script: stat.py
  login: admin
- url: /_admin/queue
  script: chatmain.py
  login: admin
- url: /
  static_files: README.html
  upload: README.html
- url: /css
  static_dir: css
- url: /img
  static_dir: img
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

inbound_services:
- xmpp_message
- xmpp_presence
- xmpp_subscribe

builtins:
- datastore_admin: on
